name = "xget-docker-proxy"
compatibility_date = "2025-09-15"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]

# Optional: Define routes for custom domain
[[routes]]
pattern = "docker-mirror.myhjwlzf.top*"
zone_name = "myhjwlzf.top"
